[package]
name = "Bitfile_reader_prototype_1"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
modular-bitfield = "0.13.0"
wasm-bindgen = "0.2.92"

[profile.release]
opt-level = "s"
lto = true
